name: build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Run npm install
        run: yarn install

      - run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  github-pages-sync:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dest
        uses: actions/download-artifact@v1
        with:
          name: build
          path: build
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build